protected/controllers/QueryController.php
<?php

Yii::setPathOfAlias('MediatoolkitSearch', Yii::getPathOfAlias('application.vendors.MediatoolkitSearch'));

class QueryController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions' => array('update','index','create','delete','view','getLinks'),
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$result=new QueryResult('search');
		$result->unsetAttributes();  // clear any default values
		if(isset($_GET['QueryResult']))
			$result->attributes=$_GET['QueryResult'];
		
		$grid_id = 'query-result-grid';

		if(Yii::app()->request->isAjaxRequest && isset($_GET['ajax']) && $_GET['ajax'] === $grid_id) {
			$this->renderPartial('_gridview_results', array(
				'model_id'=>$id,
				'result'=>$result,
			));
			Yii::app()->end();
		}
		
		$model = $this->loadModel($id);
		$siteDataProvider = new CArrayDataProvider($model->querySites);
		$siteDataProvider->setPagination(false);
                
		$this->render('view',array(
			'model'=>$model,
			'result'=>$result,
			'siteDataProvider'=>$siteDataProvider,
			'model_id'=>$id,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Query;
        $smodel = new Site;
		if(isset($_POST['Query']))
		{       
			$transaction = Yii::app()->db->beginTransaction();
			try{
				if(!isset($_POST['Query']['sites']) || !count($_POST['Query']['sites'])){
					$model->addError ('sites', 'Mora biti odabrana barem jedna stranica');
				}

				$keyword = new Keyword();
				if(isset($_POST['Query']['keyword']))
					$keyword = Keyword::getOldOrNewKeyword($_POST['Query']['keyword']);

				if(!$keyword->save()){
					$model->addError('keyword', $keyword->getError('Dogodila se pogreška prilikom pokušaja pretrage!'));
				}

				$model->keyword_id = $keyword->id;
				if($model->hasErrors() || !$model->save(true)){
					$model->keyword = $keyword->text;
					throw new Exception;
				}

				foreach($_POST['Query']['sites'] as $site){
					$qs = new QuerySite();
					$qs->site_id = $site;
					$qs->query_id = $model->id;
					$qs->status_id = 1; #  POCETNI
					$qs->save();
				}

				$transaction->commit();
				$this->redirect(array('view','id'=>$model->id));
			}
			catch (Exception $e){
				$transaction->rollback();
			}
		}
		$this->render('application.views.site.index', array(
			'model'=>$model,
			'smodel'=>$smodel,
		));
	}
        
	public function actionGetLinks($id){
		session_write_close();
		$qs = $this->loadQuerySite($id);
		if($qs->status_id == 1){
			$this->renderJSON($qs->getAndSaveLinks());
		}
		else {
			$this->renderJSON($qs->getResponse());
		}
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Query('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Query']))
			$model->attributes=$_GET['Query'];
                
		$this->render('index',array(
			'model'=>$model,
		));
	}
        
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return QuerySite the loaded model
	 * @throws CHttpException
	 */
	public function loadQuerySite($id)
	{
		$model=QuerySite::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Query the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Query::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Query $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='query-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php $this->widget('Flashes'); ?>
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Izbornik',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'sideMenu'),
		));
		$this->endWidget();
	?>
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
				'title'=>'Zadnje pretrage',
		));
		$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->recentQueries,
				'htmlOptions'=>array('class'=>'recentQueries'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Pretraga', 'url'=>array('/site/index')),
				array('label'=>'Stranice', 'url'=>array('/siteSearch/index')),
				array('label'=>'Povijest', 'url'=>array('/query/index')),
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
            'homeLink' => CHtml::link('Naslovnica', Yii::app()->homeUrl),
		)); ?><!-- breadcrumbs -->
	<?php endif?>
        
	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> Branimir Pešorda.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>