protected/controllers/QueryController.php
<?php

Yii::setPathOfAlias('MediatoolkitSearch', Yii::getPathOfAlias('application.vendors.MediatoolkitSearch'));

class QueryController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions' => array('update','index','create','delete','view','getLinks'),
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$result=new QueryResult('search');
		$result->unsetAttributes();  // clear any default values
		if(isset($_GET['QueryResult']))
			$result->attributes=$_GET['QueryResult'];
		
		$grid_id = 'query-result-grid';

		if(Yii::app()->request->isAjaxRequest && isset($_GET['ajax']) && $_GET['ajax'] === $grid_id) {
			$this->renderPartial('_gridview_results', array(
				'model_id'=>$id,
				'result'=>$result,
			));
			Yii::app()->end();
		}
		
		$model = $this->loadModel($id);
		$siteDataProvider = new CArrayDataProvider($model->querySites);
		$siteDataProvider->setPagination(false);
                
		$this->render('view',array(
			'model'=>$model,
			'result'=>$result,
			'siteDataProvider'=>$siteDataProvider,
			'model_id'=>$id,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Query;
        $smodel = new Site;
		if(isset($_POST['Query']))
		{       
			$transaction = Yii::app()->db->beginTransaction();
			try{
				if(!isset($_POST['Query']['sites']) || !count($_POST['Query']['sites'])){
					$model->addError ('sites', 'Mora biti odabrana barem jedna stranica');
				}

				$keyword = new Keyword();
				if(isset($_POST['Query']['keyword']))
					$keyword = Keyword::getOldOrNewKeyword($_POST['Query']['keyword']);

				if(!$keyword->save()){
					$model->addError('keyword', $keyword->getError('Dogodila se pogreška prilikom pokušaja pretrage!'));
				}

				$model->keyword_id = $keyword->id;
				if($model->hasErrors() || !$model->save(true)){
					$model->keyword = $keyword->text;
					throw new Exception;
				}

				foreach($_POST['Query']['sites'] as $site){
					$qs = new QuerySite();
					$qs->site_id = $site;
					$qs->query_id = $model->id;
					$qs->status_id = 1; #  POCETNI
					$qs->save();
				}

				$transaction->commit();
				$this->redirect(array('view','id'=>$model->id));
			}
			catch (Exception $e){
				$transaction->rollback();
			}
		}
		$this->render('application.views.site.index', array(
			'model'=>$model,
			'smodel'=>$smodel,
		));
	}
        
	public function actionGetLinks($id){
		session_write_close();
		$qs = $this->loadQuerySite($id);
		if($qs->status_id == 1){
			$this->renderJSON($qs->getAndSaveLinks());
		}
		else {
			$this->renderJSON($qs->getResponse());
		}
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Query('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Query']))
			$model->attributes=$_GET['Query'];
                
		$this->render('index',array(
			'model'=>$model,
		));
	}
        
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return QuerySite the loaded model
	 * @throws CHttpException
	 */
	public function loadQuerySite($id)
	{
		$model=QuerySite::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Query the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Query::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Query $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='query-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/SiteSearchController.php
<?php

Yii::setPathOfAlias('MediatoolkitSearch', Yii::getPathOfAlias('application.vendors.MediatoolkitSearch'));

class SiteSearchController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);
		$siteDataProvider = new CArrayDataProvider($model->querySites);
		$this->render('view',array(
			'model'=>$model,
			'querySiteModel'=>$siteDataProvider,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Site;
		if(isset($_POST['Site']))
		{
			$model->attributes=$_POST['Site'];
			$model->fixUrl();
			if($model->validate() && $model->createSite()){
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}
	
	public function actionCreateTEST()
	{
		$model=new Site;
		if(isset($_POST['Site']))
		{
			$model->attributes=$_POST['Site'];
			$model->fixUrl();
			
			if($model->validate() && $model->createSite()){
				echo "OK ", $model->type, ' ', $model->url_template;
			}
			else {
				echo 'GRESKA : ', ' ', $model->getErrors()['url']['0'];
			}
		}
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		if(isset($_POST['Site']['title']))
		{
			$model->title=$_POST['Site']['title'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Site('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Site']))
			$model->attributes=$_GET['Site'];
                
		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Site the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Site::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Site $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='site-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/siteSearch/_form.php
<?php
/* @var $this SiteSearchController */
/* @var $model Site */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'site-form',
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>
	
	<?php if($model->isNewRecord){ ?>
	<div class="row">
		<?php echo $form->labelEx($model,'url'); ?>
		<?php echo $form->textField($model,'url',array('size'=>60,)); ?>
		<?php echo $form->error($model,'url'); ?>
	</div>
	<?php } ?>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/siteSearch/create.php
<?php
/* @var $this SiteSearchController */
/* @var $model Site */

$this->breadcrumbs=array(
	'Stranice'=>array('index'),
	'Dodaj novu stranicu',
);

$this->menu=array(
	array('label'=>'Sve stranice', 'url'=>array('index')),
);
?>

<h1>Dodaj novu stranicu</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/siteSearch/index.php
<?php
/* @var $this SiteSearchController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Stranice',
);

$this->menu=array(
	array('label'=>'Dodaj novu stranicu', 'url'=>array('create')),
);
?>

<h1>Sve stranice</h1>

<?php 

$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'site-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
        'summaryText' => 'Prikazujem {start}-{end} od {count}',
        'emptyText' => 'Ne postoji ni jedna stranica.',
	'columns'=>array(
		array(
			'header'=>'#',
			'class'=>'CounterColumn',
		),
		array(
			'header'=>'Naslov',
			'name'=>'title',
		),
		array(
			'header'=>'URL',
			'name'=>'url',
			'type'=>'raw',
			'value'=>'CHtml::link($data->url, $data->url)',
		),
		array(
			'header'=>'Datum dodavanja',
			'name'=>'date_added',
		),
		array(
			'class'=>'CButtonColumn',
			'template'=>'{view}{delete}',
			'buttons'=>array(
				'view'=>array(
					'label'=>'Pogledaj',
				),
				'delete'=>array(
				   'label'=>'Obriši',
				),
			)
		),
	),
));

protected/views/siteSearch/update.php
<?php
/* @var $this SiteSearchController */
/* @var $model Site */

$this->breadcrumbs=array(
	'Stranice'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Uredi',
);

$this->menu=array(
	array('label'=>'Sve stranice', 'url'=>array('index')),
	array('label'=>'Dodaj novu stranicu', 'url'=>array('create')),
        array('label'=>'Pregledaj stranicu', 'url'=>array('view', 'id'=>$model->id)),
	array(
		'label'=>'Obriši stranicu', 'url'=>'#', 
		'linkOptions'=>
			array('submit'=>array('delete','id'=>$model->id),
				'confirm'=>'Jeste li sigurni da želite izbrisati stranicu?'
			)
	),
);
?>

<h1>Uredi <?php echo $model->title; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/siteSearch/view.php
<?php
/* @var $this SiteSearchController */
/* @var $model Site */

$this->breadcrumbs=array(
	'Stranice'=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>'Sve stranice', 'url'=>array('index')),
	array('label'=>'Dodaj novu stranicu', 'url'=>array('create')),
	array('label'=>'Uredi stranicu', 'url'=>array('update', 'id'=>$model->id)),
	array(
		'label'=>'Obriši stranicu', 'url'=>'#', 
		'linkOptions'=>
			array('submit'=>array('delete','id'=>$model->id),
				'confirm'=>'Jeste li sigurni da želite izbrisati stranicu?'
			)
	),
);
?>

<h1><?php echo $model->title; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'url',
		'title',
		'date_added',
		'url_template',
		'form_type',
		'type'
	),
)); ?>

<br />
<?php 
if($model->form_type == 'POST'){
	echo '<h3>POST parametri</h3>';
	$this->widget('zii.widgets.CDetailView', array(
		'data'=>$model->getSitePost(),
		'attributes'=>array(
			'post_fields',
			'boundary',
		),
	));
}?>
<br />
<h3>Pretrage</h3>
<?php 
	$this->widget('zii.widgets.grid.CGridView', array(
		'id'=>'querySite-grid',
		'dataProvider'=> $querySiteModel,
		'summaryText' => 'Prikazujem {start}-{end} od {count}',
		'emptyText' => 'Ne postoji ni jedna stranica.',
		'columns'=>array(
			array(
				'header'=>'#',
				'class'=>'CounterColumn',
			),
			array(
				'header'=>'Ključna riječ',
				'type'=>'raw',
				'htmlOptions'=>array(
					'width'=>'200',
				 ),
				'value'=>'$data->keyword->text',
			),
			array(
				'header'=>'Status',
				'type'=>'raw',
				'value'=>'$data->status->text',
			),
			array(
				'header'=>'Broj rezultata',
				'type'=>'raw',
				'htmlOptions'=>array(
					'width'=>'55',
				 ),
				'value'=>'$data->query_result_num',
			),
			array(
				'header'=>'Početak obrade',
				'type'=>'raw',
				'value'=>'$data->query_start',
			),
			array(
				'header'=>'Kraj obrade',
				'type'=>'raw',
				'value'=>'$data->query_finish',
			),
			array(
				'class'=>'CButtonColumn',
				'template'=>'{view}',
				'buttons'=>array(
					'view'=>array(
						'label'=>'Pogledaj',
						'url'=>'Yii::app()->createUrl("query/view", array("id"=>$data->query->id))',
					),
				)
			),
		),
	));
	?>